"""first migrate

Revision ID: e2276367f572
Revises: 
Create Date: 2021-03-21 02:46:42.552132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2276367f572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('client_message', sa.String(length=1000), nullable=True),
    sa.Column('bot_message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###
